directories:
  output: dist-electron
  buildResources: build
appId: com.clipboard.monitor
productName: 剪切板监控器
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
  icon: electron/icon.png
  requestedExecutionLevel: asInvoker
mac:
  target: dmg
  icon: electron/icon.png
linux:
  target: AppImage
  icon: electron/icon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: 剪切板监控器
electronVersion: 28.3.3
